platform :ios, ‘8.0'
target ‘Product-B’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.6'
pod 'FMDB', '~> 2.6.2'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'DACircularProgress', '~> 2.3.1'
pod 'MJExtension', '~> 3.0.10'
pod 'DACircularProgress', '~> 2.3.1'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'pop', '~> 1.0.9'
pod 'AVOSCloud', '~> 3.3.3'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'AVOSCloud', '~> 3.3.3'
pod 'DKNightVersion', '~> 2.3.0'
end

